// Generated by the protocol buffer compiler.  DO NOT EDIT!


#import "ProtocolBuffers.h"
// @@protoc_insertion_point(imports)

@class Message;
@class MessageBuilder;



@interface MessageProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Message_protocol @"protocol"
#define Message_body_length @"bodyLength"
#define Message_package_id @"packageId"
#define Message_body @"body"
@interface Message : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasProtocol_:1;
  BOOL hasBodyLength_:1;
  BOOL hasPackageId_:1;
  BOOL hasBody_:1;
  SInt32 protocol;
  SInt32 bodyLength;
  NSString* packageId;
  NSString* body;
}
- (BOOL) hasProtocol;
- (BOOL) hasBodyLength;
- (BOOL) hasPackageId;
- (BOOL) hasBody;
@property (readonly) SInt32 protocol;
@property (readonly) SInt32 bodyLength;
@property (readonly, strong) NSString* packageId;
@property (readonly, strong) NSString* body;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBuilder*) builder;
+ (MessageBuilder*) builder;
+ (MessageBuilder*) builderWithPrototype:(Message*) prototype;
- (MessageBuilder*) toBuilder;

+ (Message*) parseFromData:(NSData*) data;
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromInputStream:(NSInputStream*) input;
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBuilder : PBGeneratedMessageBuilder {
@private
  Message* resultMessage;
}

- (Message*) defaultInstance;

- (MessageBuilder*) clear;
- (MessageBuilder*) clone;

- (Message*) build;
- (Message*) buildPartial;

- (MessageBuilder*) mergeFrom:(Message*) other;
- (MessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProtocol;
- (SInt32) protocol;
- (MessageBuilder*) setProtocol:(SInt32) value;
- (MessageBuilder*) clearProtocol;

- (BOOL) hasBodyLength;
- (SInt32) bodyLength;
- (MessageBuilder*) setBodyLength:(SInt32) value;
- (MessageBuilder*) clearBodyLength;

- (BOOL) hasPackageId;
- (NSString*) packageId;
- (MessageBuilder*) setPackageId:(NSString*) value;
- (MessageBuilder*) clearPackageId;

- (BOOL) hasBody;
- (NSString*) body;
- (MessageBuilder*) setBody:(NSString*) value;
- (MessageBuilder*) clearBody;
@end


// @@protoc_insertion_point(global_scope)
